# Generated by Django 4.1.1 on 2023-04-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pactientaccount',
            name='confirmpassword',
        ),
    ]
