# Generated by Django 4.1.1 on 2023-04-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_rename_firstname_account_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='DocOrPat',
            field=models.TextField(choices=[('doctor', 'doctor'), ('patient', 'patient')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='payMethod',
            field=models.TextField(choices=[('cash', 'cash'), ('paypal', 'paypal'), ('visa', 'visa')]),
        ),
    ]
