# Generated by Django 4.1.1 on 2023-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_account_docorpat_alter_account_paymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='proPic',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
