# Generated by Django 4.1.1 on 2023-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_account_dateofbirth_alter_account_docorpat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
