# Generated by Django 4.1.1 on 2023-06-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_account_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
